# Generated by Django 5.0.3 on 2024-03-16 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('tag', models.CharField(max_length=4)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'users',
                'unique_together': {('username', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='LoginUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login', to='authentication.usermodel')),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
