# Generated by Django 5.0.3 on 2024-03-16 21:02

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginusermodel',
            name='date_time',
        ),
        migrations.AddField(
            model_name='loginusermodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loginusermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='ip_address',
            field=models.CharField(default=datetime.datetime(2024, 3, 16, 21, 2, 30, 225024, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='isp',
            field=models.CharField(default=datetime.datetime(2024, 3, 16, 21, 2, 43, 765865, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='location',
            field=models.CharField(default=datetime.datetime(2024, 3, 16, 21, 2, 51, 185159, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
