# Generated by Django 5.0.3 on 2024-03-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_loginusermodel_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.TextField(),
        ),
    ]
