# Generated by Django 5.0.3 on 2024-03-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kayo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
